# Generated by Django 4.0.4 on 2022-04-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messager', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='users_followers', to='messager.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='user_follows', to='messager.profile'),
        ),
    ]
