# Generated by Django 4.0.4 on 2022-04-13 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messager', '0003_profile_followers_alter_profile_follows'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='owner',
        ),
    ]
