# Generated by Django 4.0.4 on 2022-04-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messager', '0004_rename_user_message_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked', to='messager.profile'),
        ),
    ]
